### ISSUE TITLE
doesn't work for ipf files

### ISSUE THREAD

**Issue by medievil1** [solarmon/UCG#1]
my collection is in ipf format... using it with retroarch and creating my own .uae, p-uae will load the files perfectly fine. 
I tried changing the .py and replacing adf with ipf but apparently I have the wrong version of py installed as I get :
  File "Y:\retroarch\UCG\ucg.py", line 350
    print('  +---[GAME] ',Fore.GREEN,game_name,Style.RESET_ALL,' (',file_extension,')',sep='')
                                                                                                                                            ^
SyntaxError: invalid syntax

ipf format is very important since it is the only true way to have perfect backups of the original amiga disks

**Comment by solarmon** [comment]
@medievil1 

Apologies for the delay in responding to this ticke.

IPF files not supported at the moment, but I will look in whether it can be supported.

**Comment by medievil1** [comment]
> 
> 
> @medievil1
> 
> Apologies for the delay in responding to this ticke.
> 
> IPF files not supported at the moment, but I will look in whether it can be supported.

no worries, puae in retroarch supports them now, don't even need a cfg anymore, but for standalone amiga emu's ipf would definitely be a good addition

**Comment by solarmon** [comment]
@medievil1 

IPF support has now been added, but not tested, in release v0.6-beta

https://github.com/solarmon/UCG/releases/tag/v0.6-beta
