### ISSUE TITLE
Fail generating uae

### ISSUE THREAD

**Issue by John3d** [solarmon/UCG#2]
Hi
I test his program in windows 7 64 bits and run but this error appear:

![UCG](https://user-images.githubusercontent.com/21139065/73836484-a9e09b00-480f-11ea-9176-cb34d3723be2.png)

**Comment by solarmon** [comment]
@John3d

Apologies for the delay in responding to this ticket.

I know this was initially covered in the EAB forum, but I'd like to start understanding the issue again.

Please let me know when you are getting this error and what game files you are trying to get UCG to generate UAE config files for - give some example game files.

Thank you.

**Comment by John3d** [comment]
This error appear when game files are *.lha

**Comment by solarmon** [comment]
@John3d 

I can't seem to replicate this in my test environment.

Can you confirm what UCG version you are using and an example of the LHA filename, and the LHA file itself - link to the source of this LHA file.

**Comment by John3d** [comment]
I use version UCG-v0.5-beta. 

I have even tried version UCG-v0.4-beta and the same thing happens.

LHA files are from http://whdload.de/games/A0-Ak.html (Aaargh.lha and Agony.lha) 

More info in snap:

![Sin título-1](https://user-images.githubusercontent.com/21139065/87246093-3b050f00-c44b-11ea-86b6-391880da28d0.png)

**Comment by solarmon** [comment]
Aaargh!

Literally. The filenames in the the Aaargh.lha file has an exclamation mark in it so I think this is what is breaking. The GUI seems to be displaying it OK (in Game Files and Game List tabs - please can you confirm this is the case for you too.

I need to find out why the debug output function is not able to handle the exclamation mark and how to escape these 'special' characters.

**Comment by John3d** [comment]
![Sin título2](https://user-images.githubusercontent.com/21139065/87255921-29ddf180-c48f-11ea-9b60-d2226390cf5a.png)
![Sin título3](https://user-images.githubusercontent.com/21139065/87255929-2e0a0f00-c48f-11ea-9929-9285aa9d6f92.png)

I have tasted and if I delete Aaargh.lha, i have the same error

**Comment by solarmon** [comment]
Yes, I did find that out too. The exclamation mark was a red herring. But it help me identify the issue in the code.

I will hopefully release a new version soon that will fix it.

**Comment by solarmon** [comment]
@John3d 

The logging error for .lha files should now be fixed release v0.6-beta:

https://github.com/solarmon/UCG/releases/tag/v0.6-beta

Thank you for reporting this issue and sorry it took so long to be looked at and fixed.
